package com.example.reyclerviewkotlin

import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val superheroList = listof<Superhero>(
            Superhero(
                R.drawable.antman,
                nameSuperhero = "Antman",
                descriptionSuperhero = "Pada tahun 1989, ilmuwan Hank Pym mengundurkan diri dari S.H.I.E.L.D. setelah menemukan bahwa mereka berusaha untuk meniru teknologi menyusut Ant-Man nya. Percaya teknologi ini berbahaya, Pym bersumpah untuk menyembunyikannya selama ia hidup. Pada hari ini, putri terasing Pym, Hope van Dyne, dan mantan anak didik, Darren Cross, telah memaksa dia keluar dari perusahaan sendiri. Cross hampir menyempurnakan setelan baju penyusut miliknya sendiri, Yellowjacket, yang mengangetkan Pym.\n" +
                        "\n" +
                        "Setelah dibebaskan dari penjara, pencuri ulung Scott Lang bergerak dengan teman satu sel lamanya, Luis. Mantan istri Lang, Maggie. yang bertunangan dengan polisi Paxton-setuju untuk membiarkan Lang melihat putrinya Cassie jika ia memberikan dukungan kepada anaknya. Tidak dapat menahan pekerjaan karena catatan kriminalnya, Lang setuju untuk bergabung dengan Luis kru dan melakukan perampokan uang. Lang menerobos masuk ke dalam rumah dan menerobosnya dengan aman, tetapi ia hanya menemukan setelan kostum motor tua, yang kemudia ia bawa ke rumah. Setelah mencoba kostum itu, Lang tanpa sengaja menyusutkan dirinya menjadi seukuran serangga. Ketakutan dari pengalaman itu , ia kembali ke rumah di mana kostum itu berada, tetapi ditangkap ketika dia keluar dari rumah itu. Pym, sang pemilik rumah, mengunjungi Lang di penjara dan menyelundupkan kostum itu untuk membantu dia keluar.\n" +
                        "\n" +
                        "Di rumahnya, Pym, yang memanipulasi Lang melalui Luis untuk mencuri kostum itu dianggapnya sebagai ujian, dia ingin Lang menjadi Ant-Man baru untuk mencuri Yellowjacket dari Cross. Van Dyne, yang telah memata-matai Cross untuk Pym meskipun hubungannya tidak baik dengan ayahnya, membantu Pym melatih Lang untuk melawan dan mengendalikan semut. Mereka mengirimnya untuk mencuri perangkat dari markas Avengers, di mana ia sempat bertarung dengan Sam Wilson. Sementara van Dyne masih menunjukkan kemarahan terhadap Pym tentang kematian ibunya, Janet, dia mengungkapkan bahwa Janet, yang dikenal sebagai Wasp, menghilang menjadi kuantum subatomik untuk menonaktifkan rudal nuklir Soviet. Pym memperingatkan Lang bahwa dia bisa mengalami nasib yang sama jika ia mengabaikan perlindungan kostumnya.\n" +
                        "\n" +
                        "Cross menyempurnakan Yellowjacket dan mengundang Pym untuk datang ke upacara pembukaan. Lang, bersama dengan kru dan segerombolan semut terbang, menyusup di bangunan tersebut selama acara, menyabotase server, dan menanamkan bahan peledak. Ketika ia mencoba untuk mencuri Yellowjacket, dia terperangkap oleh Cross, yang bermaksud untuk menjual kedua kostum yaitu Yellowjacket dan Ant-Man untuk Hydra, yang dipimpin oleh Mitchell Carson. Lang berhasil bebas dan mengalahkan sebagian besar agen Hydra, meskipun Carson mampu melarikan diri dengan botol partikel milik Cross. Lang mengejar Cross saat ia lolos, ketika ia mengaktifkan detonator bom, meluluhlantakan bangunan tersebut.\n" +
                        "\n" +
                        "Cross menggunakan kostum Yellowjacket dan bertarung dengan Lang. Sampai akhirnya Lang ditangkap oleh Paxton. Pikirannya yang kacau oleh teknologi menyusut tidak sempurna, Cross menjadikan Cassie sandera untuk memikat Lang dalam pertarungan lain, kali ini, Lang menyusut ke ukuran subatomik menembus YellowJacket milik Cross dan proses sabotase menyusut tak terkendali, membunuh Cross. Lang menghilang ke dalam dunia kuantum tetapi berhasil membalikkan mekanisme setelan kostum itu dan kembali ke dunia nyata. Dalam rasa syukur atas kepahlawanan Lang, Paxton mengatakan pada Lang dan membebaskannya dari penjara. Melihat bahwa Lang selamat dan kembali dari alam kuantum, Pym bertanya apakah istrinya masih hidup juga. Kemudian, Lang bertemu dengan Luis, yang mengatakan kepadanya bahwa Wilson sedang mencari dia.\n" +
                        "\n" +
                        "Dalam sebuah adegan mid-credits, Pym menunjukkan van Dyne sebuah kostum baru Wasp dan menawarkan kepadanya. Dalam sebuah adegan post-credit, Wilson dan Steve Rogers mencari Bucky Barnes. Wison menyuruh Rogers untuk menghubungi Tony Stark, tetapi Rogers tidak ingin. Wilson menyebutkan bahwa ia \"tahu seorang pria yang bisa melakukannya\"."
                ),
                 Superhero(
                     R.drawable.batman,
                     nameSuperhero = "Batman",
                     descriptionSuperhero = "Batman adalah tokoh fiksi pahlawan super yang diciptakan oleh seniman Bob Kane dan penulis Bill Finger[1][2] dan diterbitkan oleh DC Comics. Tokoh ini pertama muncul di Detective Comics #27 (Mei 1939). Identitas asli Batman adalah Bruce Wayne, seorang pengusaha yang kaya raya. Nama Bruce Wayne itu sendiri diambil dari nama tokoh sejarah, yaitu Robert the Bruce dan Anthony Wayne.[5]\n" +
                             "\n" +
                             "Identitas rahasia Batman adalah Bruce Wayne, playboy Amerika yang kaya, dermawan, dan pemilik Wayne Enterprises. Setelah menyaksikan pembunuhan orang tuanya, Dr. Thomas Wayne dan Martha Wayne ketika masih anak-anak, ia bersumpah membalas dendam terhadap para penjahat, sebuah sumpah yang digerakkan oleh rasa keadilan. Bruce Wayne melatih dirinya sendiri secara fisik dan intelektual dan menciptakan kepribadian yang terinspirasi kelelawar untuk memerangi kejahatan.[6]\n" +
                             "\n" +
                             "Batman beroperasi di Gotham City, dibantu oleh Alfred Pennyworth (butler) dan rekannya Robin. Tidak seperti pahlawan super kebanyakan, dia tidak memiliki kekuatan super, ia hanya menggunakan intelegensi, keterampilan sebagai detektif, ilmu pengetahuan dan teknologi, kekayaan, ketangkasan fisik, dan intimidasi dalam memerangi kejahatan.\n" +
                             "\n" +
                             "Batman menjadi karakter terkenal dengan cepat setelah diperkenalkan di Detective Comics untuk pertama kali, dan akhirnya dirilis komik dengan judul Batman. Setelah satu dasawarsa pemakaian judul tersebut, perbedaan karakter telah muncul. Pada akhir tahun 1960-an, karakter Batman dalam serial televisi diubah menjadi lebih estetika selama bertahun-tahun sampai ceritanya usai"
                 ),
                 Superhero(
                     R.drawable.hulk,
                     nameSuperhero = "Hulk",
                     descriptionSuperhero = "Hulk, adalah tokoh pahlawan super fiksi yang ada pada Marvel Comics. DIciptakan oleh Stan Lee dan Jack Kirby, tokoh ini pertama kali muncul di The Incredible Hulk #1 (Mei 1962). Pada tahun 2008, majalah Wizard memberikan julukan kepada Hulk sebagai tokoh dari ketujuh Marvel Comics terhebat[3] Empire Magazine menamakannya sebagai keempat belas tokoh komik dan rangking lima terbesar dari Marvel.[4]\n" +
                             "\n" +
                             "Hulk diciptakan sebagai orang yang memiliki alter ego hasrat dan emosional yang bisa mengubah fisik seorang Dr. Bruce Banner. Hulk muncul setelah Banner secara tidak sengaja terkena test ledakan dari bom gamma yang ia temukan. Sesudah kejadian itu, Banner akan berubah menjadi Hulk, digambarkan sebagai seorang raksasa, monster humanoid, mengarahkan kehidupan Banner menjadi sangat rumit. Dikatakan oleh Stan Lee, Hulk diinspirasikan oleh kombinasi antara tokoh Dr. Jekyll and Mr. Hyde, dan Frankenstein.[5] Meskipun ada keinginan Hulk dan Banner untuk menyepi, karakter tersebut memiliki pemain pendukung yang hebat, termasuk kekasih Banner Betty Ross, temannya Rick Jones, sepupunya She-Hulk, anak laki-laki Hiro-Kala dan Skaar, dan rekan pendiri tim superhero Avengers. Namun, kekuatannya yang tak terkendali telah membuatnya terlibat konflik dengan sesama pahlawan dan lainnya.\n" +
                             "\n" +
                             "Walaupun pewarnaan kulit Hulk bermacam-macam dari berbagai sejarah publikasi, yang paling sering di publikasikan adalah kulitnya yang berwarna hijau. Sebagai Hulk, Banner sanggup memunculkan kekuatan luar biasa, sejalan dengan tingkat kemarahan tokoh ini. Emosi yang kuat seperti kemarahan, teror dan kesedihan juga menjadi pemicu perubahan fisik Banner menajadi Hulk. Alur cerita yang sering dipublikasikan adalah antara Banner dan Hulk sering dikejar oleh polisi dan Angkatan bersenjata karena pengerusakan yang telah ia lakukan."
                 ),
                 Superhero(
                     R.drawable.iron,
                     nameSuperhero = "Ironman",
                     descriptionSuperhero = "Pada adegan intro, Tony Stark digambarkan sedang berbincang dengan beberapa tentara dalam kendaraan militer, sebelum mereka diserang oleh kelompok teroris. Stark terkena ledakan rudal yang ternyata merupakan produk buatan perusahaannya sendiri. Setelah itu dia disandera oleh kelompok tersebut.\n" +
                             "\n" +
                             "Tony Stark yang mewarisi perusahan kontraktor pertahanan Stark Industries dari mendiang ayahnya, digambarkan sebagai seorang genius yang berhasil mengembangkan teknologi persenjataan militer. Namun, dia juga digambarkan sebagai seseorang yang senang berjudi dan bermain-main dengan wanita. Demi urusan bisnis, dia pergi ke Afganistan yang luluh lantak oleh perang bersama teman sekaligus penghubung militernya, Letnan Kolonel James Rhodes untuk mendemonstrasikan peluru kendali \"Jericho\" yang baru. Kenudian adegan dipercepat, dengan menampilan penggalan ketika rombongan Stark disergap, Stark terluka oleh rudal, dan tindakan operasi yang dilakukan kepadanya. Setelah bangun ia mendapati dirinya ditangkap dan ditawan dalam sebuah gua oleh kelompok teroris bernama Ten Rings. Ho Yinsen, yang merupakan seorang dokter dan sesama tawanan, menanamkan elektromagnet ke dalam dada Stark untuk mencegah pecahan peluru yang melukainya agar tidak mencapai jantung dan membunuhnya. Pemimpin Ten Rings, Raza, menawarkan untuk membebaskan Stark dengan syarat dia membuatkan rudal Jericho untuk kelompok itu, tetapi Stark dan Yinsen tahu bahwa dia tidak akan menepati janjinya.\n" +
                             "\n" +
                             "Selama dikurung, Stark dan Yinsen diam-diam menciptakan sebuah generator listrik yang kecil dan kuat bernama arc reactor untuk memberi daya pada elektromagnet di dada Stark, serta sebuah purwarupa baju besi yang kuat untuk membantu mereka melarikan diri. Mereka berusaha untuk menyembunyikan baju besi tersebut setidaknya sebelum pembuatannya selesai, tetapi akhirnya ketahuan dan kelompok teroris itu menyerang bengkel mereka. Yinsen mengorbankan diri dengan mengalihkan perhatian mereka sementara Stark mengisi daya baju besinya. Stark yang memakai baju itu berjuang meloloskan diri dari gua dan menemukan Yinsen yang sekarat. Lalu dia membakar semua amunisi teroris dan terbang melarikan diri, sebelum akhirnya dia jatuh menghantam permukaan gurun dan merusak baju tersebut. Setelah diselamatkan oleh Rhodes, Stark pulang dan kemudian mengumumkan bahwa perusahaannya tidak akan lagi memproduksi senjata. Obadiah Stane, teman lama ayah dan manager di perusahaan Stark, memeringatkan bahwa keputusan tersebut mungkin akan merusak Stark Industries dan warisan ayahnya. Di ruang kerja di rumah Stark, dia membuat baju baja yang lebih kuat daripada sebelumnya serta arc reactor yang lebih kuat untuk baju baja dan dadanya. Asisten pribadi Stark, Pepper Potts, menempatkan reaktor asli ke dalam sebuah etalase kaca kecil. Meskipun Stane meminta perincian yang detail, Stark yang curiga memutuskan untuk merahasiakan karyanya tersebut untuk dirinya sendiri.\n" +
                             "\n" +
                             "Dalam sebuah acara amal yang diadakan oleh Stark Industries, seorang reporter, Christine Everhart memberi tahu Stark bahwa senjata-senjata buatan perusahaannya baru-baru ini dikirimkan kepada Ten Rings dan digunakan untuk menyerang kampung halaman Yinsen, Gulmira. Stark mengenakan baju besinya yang baru, lalu terbang ke Afganistan dan menyelamatkan penduduk desa. Dalam perjalanan pulang, Stark diserang oleh dua jet tempur F-22 Raptor milik Angkatan Bersenjata Amerika Serikat. Dia mengungkapkan identitas rahasianya kepada Rhodes melalui telepon agar serangan yang dilancarkan kepada dia segera dihentikan, tetapi akhirnya harus menyelamatkan seorang pilot jet yang terjun bebas. Sementara itu, Ten Rings, yang mengumpulkan potongan-potongan dari purwarupa baju besi Stark yang telah hancur, bertemu dengan Stane, yang ternyata merupakan pelaku pemasok perdagangan senjata ilegal ke Ten Rings dan perekrut Ten Rings yang ditugaskan untuk membunuh Stark sehingga dia tergguling dari posisi sebagai CEO Stark Industries. Setelah mendapat semua potongan tersebut, Stane dan pasukannya melumpuhkan Raza dan membunuh para teroris lainnya, kemudian menyuruh orang untuk melakukan rekayasa balik pada purwarupa tersebut.\n" +
                             "\n" +
                             "Stark mengirim Potts untuk meretas basis data perusahaan untuk melacak jejak perdagangan ilegal di perusahaannya. Dia menemukan bahwa Stane menyewa Ten Rings untuk membunuh Stark, tetapi kelompok tersebut mengingkari kesepakatan setelah mengetahui identitas Stark yang memiliki akses langsung ke persenjataan perusahaan. Potts langsung bertemu dengan Agen Phil Coulson dari S.H.I.E.L.D., sebuah badan inteligen, untuk melaporkan aktivitas gelap Stane. Stane yang menyadari bahwa ia ketahuan melihat perkembangan rekayasa tersebut. Akan tetapi, para ilmuwan yang bekerja di bawah Stane tidak dapat menduplikasi arc reactor buatan Stark, sehingga Stane kemudian melumpuhkan Stark di rumahnya dan mengambil arc reactor dari dada Stark. Untungnya, Stark berhasil menaruh arc reactor asli di dadanya sehingga nyawanya terselamatkan.\n" +
                             "\n" +
                             "Potts dan beberapa agen S.H.I.E.L.D. berusaha untuk menangkap Stane, tetapi Stane menggunakan baju besi hasil rekayasa, Iron Monger, untuk menyerang mereka. Stark pergi menyelamatkan mereka dan melawan Stane, tetapi dia ditekan dan dipojokkan oleh Stane karena arc reactor yang lama tidak bisa memberikan daya maksimal untuk baju besinya. Mereka bertarung hingga sampai di atap bangunan Stark Industries. Stark kemudian menyuruh Potts untuk memaksimalkan beban daya reactor arc besar yang memberi daya listrik pada gedung tersebut. Lonjakan listrik yang sangat besar dilepaskan sekaligus dan hal itu membuat Stane pingsan dan jatuh ke dalam reactor arc yang kemudian meledak dan membunuhnya. Pada hari berikutnya, Stark dalam konferensi pers memberitahukan kepada para wartawan bahwa \"Iron Man\", julukan pahlawan super yang diberikan oleh pers untuk Stark dalam baju besinya, adalah dirinya"
                 ),
                  Superhero(
                      R.drawable.nebula,
                      nameSuperhero = "Nebula",
                      descriptionSuperhero = "Banner, Lang, Rogers, dan Stark pergi ke Kota New York pada tahun 2012. Banner mengunjungi Sanctum Sanctorum dan meyakinkan Ancient One untuk memberinya Batu Waktu. Rogers berhasil mengambil Batu Pikiran, namun Stark dan Lang tidak sengaja membiarkan Loki dari tahun 2012 untuk kabur dengan Batu Angkasa. Rogers dan Stark pergi ke markas S.H.I.E.L.D. pada tahun 1970, dimana Stark mengambil versi awal dari Batu Angkasa dan bertemu dengan Howard Stark muda saat mengambilnya, sedangkan Rogers mengambil beberapa Partikel Pym dari Hank Pym untuk kembali ke masa kini. Rocket dan Thor pergi ke Asgard pada tahun 2013, mengekstrak Batu Realita dari Jane Foster dan mengambil palu Thor, Mjolnir. Nebula dan Rhodes pergi ke Morag pada tahun 2014 dan mencuri Batu Kekuatan sebelum Peter Quill dapat mencurinya. Rhodes kembali ke masa kini dengan Batu Kekuatan, namun Nebula tidak sadarkan diri ketika implan cyberneticnya berhubungan dengan dirinya dari masa lalu. Melalui hubungan ini, Thanos 2014 mempelajari mengenai keberhasilannya di masa depan dan keinginan Avengers untuk membalikkannya. Thanos menangkap Nebula 2023 dan mengirim Nebula 2014 ke masa kini untuk menggantikannya. Barton dan Romanoff pergi ke Vormir, dimana sang penjaga Batu Jiwa, Red Skull, memberitahu mereka bahwa batu tersebut hanya dapat diambil dengan mengorbankan seseorang yang mereka cintai. Romanoff mengorbankan dirinya, dan Barton mengambil Batu Jiwa.\n" +
                              "\n"
                  ),
                   Superhero(
                       R.drawable.spiderman,
                       nameSuperhero = "Spider-man",
                       descriptionSuperhero = "Nama asli Spider-Man adalah Peter Parker. Ia tinggal bersama paman dan bibinya di sebuah apartemen di Queens, Manhattan. Sejak kecil ia sudah menyukai tetangganya yang bernama Mary Jane Watson. Awal mula ia menjadi Spider-Man ialah ketika ia mengunjungi sebuah institut milik Norman Osborn. Sebuah laba-laba beradioaktif menggigitnya yang kemudian membuat Peter memiliki kekuatan laba-laba super. Dalam ceritanya Spider-Man (juga biasa disingkat \"Spidey\")."
                   ),
                   Superhero(
                       R.drawable.superman,
                       nameSuperhero = "Super-man",
                       descriptionSuperhero = "Ketika Jerry Siegel dan Joe Shuster pertama kali membuat Superman, bukanlah seorang pahlawan super yang selalu membantu manusia lain, tetapi seorang psikopat botak jenius dengan kekuatan telepati yang hendak menguasai seluruh dunia. Ia muncul pada cerita pendek yang berjudul \"The Reign of the Super-Man\" dari Science Fiction #3, sebuah majalah yang diterbitkan oleh Siegel pada tahun 1933.[7] Karena tidak lakunya karakter ini, pada akhirnya \"Superman Botak\" itu pun kemudian ditulis ulang oleh Siegel pada tahun 1933 sebagai seorang pahlawan, berbeda dari karakter jahat sebelumnya, mengambil model dari aktor Douglas Fairbanks Sr. dan alter egonya Clark Kent, dari aktor komedi Harold Lloyd.[8][9] Superman botak dan jahat kemudian menjadi seorang musuh utama Superman yang bernama Lex Luthor."
                   ),
                   Superhero(
                       R.drawable.thor,
                       nameSuperhero = "Thor",
                       descriptionSuperhero = "Pada tahun 965 M, Odin, raja Asgard, berperang melawan Frost Giants dari Jotunheim dan pemimpin mereka Laufey, untuk mencegah mereka menaklukkan sembilan wilayah, dimulai dengan Bumi. Pedang Asgardian mengalahkan Giant Frost dan merebut sumber kekuatan mereka, Casket of Ancient Winters.\n" +
                               "\n" +
                               "Saat ini, anak Odin Thor bersiap naik ke takhta Asgard, namun terputus saat Frost Giants mencoba mengambil peti mati tersebut. Atas perintah Odin, Thor pergi ke Jotunheim untuk menghadapi Laufey, didampingi oleh adiknya Loki, teman masa kecil Sif dan Warriors Three: Volstagg, Fandral, dan Hogun. Pertarungan terjadi kemudian sampai Odin melakukan intervensi untuk menyelamatkan orang-orang Asgardian, menghancurkan gencatan senjata yang rapuh antara kedua ras tersebut. Untuk arogansi Thor, Odin menanggalkan anaknya dari kekuatan dewa dan mengusirnya ke Bumi sebagai makhluk fana, ditemani oleh palu Mjolnir, yang sekarang dilindungi oleh pesona yang memungkinkan hanya yang layak untuk menggunakannya.\n" +
                               "\n" +
                               "Thor mendarat di New Mexico, di mana astrofisikawan Dr. Jane Foster, asistennya Darcy Lewis, dan mentor Dr. Erik Selvig, menemukannya. Penduduk setempat menemukan Mjolnir, agen S.H.I.E.L.D. Phil Coulson segera menjadi komandan sebelum secara paksa memperoleh data Jane tentang lubang cacing yang mengantarkan Thor ke Bumi. Thor, yang telah menemukan lokasi terdekat Mjolnir, berusaha mengambilnya dari fasilitas yang S.H.I.E.L.D. dengan cepat dibangun tapi dia mendapati dirinya tidak mampu mengangkatnya, dan ditangkap. Dengan bantuan Selvig, dia dibebaskan dan mengundurkan diri untuk diasingkan di Bumi saat dia mengembangkan percintaan dengan Jane.\n" +
                               "\n" +
                               "Loki menemukan bahwa dia adalah anak biologis Laufey, diadopsi oleh Odin setelah perang usai. Seorang Odin yang letih jatuh ke dalam \"Odinsleep\" yang dalam untuk memulihkan kekuatannya. Loki merebut takhta pengganti Odin dan menawarkan kesempatan kepada Laufey untuk membunuh Odin dan merebut peti mati tersebut. Sif dan Warriors Three, yang tidak senang dengan peraturan Loki, mencoba mengembalikan Thor dari pengasingan, meyakinkan Heimdall, penjaga gerbang Bifröst — sarana untuk melakukan perjalanan di antara dunia — untuk memungkinkan mereka masuk ke Bumi. Sadar akan rencana mereka, Loki mengirim Destroyer, robot yang tampaknya tidak bisa dihancurkan, untuk mengejar mereka dan membunuh Thor. Para pejuang menemukan Thor, namun serangan Destroyer dan mengalahkan mereka, mendorong Thor untuk menawarkan dirinya sebagai gantinya. Dipukul oleh Destroyer dan menjelang kematian, pengorbanan Thor membuktikan dia layak untuk menggunakan Mjolnir. Palu kembali kepadanya, memulihkan kekuatannya dan memungkinkannya mengalahkan Destroyer. Ciuman selamat tinggal Jane dan bersumpah untuk kembali, dia dan rekan-rekan Asgardiannya pergi untuk menghadapi Loki.\n" +
                               "\n" +
                               "Di Asgard, Loki mengkhianati dan membunuh Laufey, mengungkapkan rencananya yang sebenarnya untuk menggunakan usaha Laufey pada kehidupan Odin sebagai alasan untuk menghancurkan Jotunheim dengan Jembatan Bifröst, sehingga membuktikan dirinya layak untuk ayah angkatnya. Thor datang dan melawan Loki sebelum menghancurkan Jembatan Bifröst untuk menghentikan rencana Loki, menandingi dirinya di Asgard. Odin membangunkan dan mencegah saudara-saudaranya jatuh ke dalam jurang yang tercipta setelah penghancuran jembatan, tapi Loki membiarkan dirinya jatuh saat Odin menolak permintaannya untuk mendapatkan persetujuan. Thor menebus kesalahannya dengan Odin, mengakui bahwa dia belum siap untuk menjadi raja; sementara di Bumi, Jane dan timnya mencari cara untuk membuka portal ke Asgard.\n"
                   )
            )

        val recyclerView = findViewById<RecyclerView>(R.id.rv_hero)
        recyclerView.layoutManager = LinearLayoutManager(this )
        recyclerView.setHasFixedSize(true)
        recyclerView.adapter = SuperheroAdaptor(this, superheroList){

        }
    }

    private fun <T> listof(
        superhero: T,
        superhero1: T,
        superhero2: T,
        superhero3: T,
        superhero4: T,
        superhero5: T,
        superhero6: T,
        superhero7: T
    ) = Unit
    }


